### ISSUE TITLE
老大，没有前一个标签，后一个标签的手势

### ISSUE THREAD

**Issue by tgzw1680** [woolition/greasyforks#8]
很好的脚本，感谢老大，能否添加前一个标签，后一个标签的手势？或者自定义如何写。。。码盲。。。

**Comment by woolition** [comment]
这个功能实现不了。因为Tampermonkey的脚本权限只能操作本标签，无法操作别的标签。所以前一个标签，后一个标签，这个功能实现不了。

**Comment by woolition** [comment]
暂时没有办法实现这个功能。Tampermonkey执行的脚本只能作用于本标签，无法操作其他标签。

2018-03-09 13:58 GMT+08:00 tgzw1680 <notifications@github.com>:
